# Generated by Django 4.2.2 on 2023-06-18 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('bio', models.TextField()),
                ('age', models.IntegerField(max_length=10)),
                ('thumbnail', models.ImageField(default='blank-profile-picture.png', upload_to='artist_image')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(default='blank-profile-picture.png', upload_to='genres')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('thumbnail', models.ImageField(default='blank-profile-picture.png', upload_to='song_images')),
                ('size', models.IntegerField(max_length=10)),
                ('song', models.FileField(upload_to='songs')),
                ('playtime', models.CharField(default='0.00', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.artist')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.genre')),
            ],
        ),
    ]
