# Generated by Django 4.2.2 on 2023-06-18 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='discription',
            new_name='description',
        ),
    ]
