# Generated by Django 4.2.2 on 2023-06-18 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_discription_song_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='playtime',
        ),
    ]
