# Generated by Django 4.2.2 on 2023-06-18 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_song_playtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='size',
        ),
    ]
