# Generated by Django 4.2.2 on 2023-06-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_song_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='age',
        ),
        migrations.AddField(
            model_name='artist',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
