# Generated by Django 4.2.2 on 2023-06-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_artist_age_artist_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='birthday',
        ),
        migrations.AddField(
            model_name='artist',
            name='country',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
