# Generated by Django 4.2.2 on 2023-06-19 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_artist_birthday_artist_country'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artist',
            table='core_artist',
        ),
    ]
