# Generated by Django 4.2.2 on 2023-06-19 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_song_song_audio_alter_artist_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artist_name',
            new_name='artist_id',
        ),
    ]
