# Generated by Django 4.2.2 on 2023-06-19 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_artist_name_song_artist_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artist_id',
            new_name='artist',
        ),
    ]
